fix: remove try catch in run method
This causes paste exceptions thrown by helper functions to be encapsulated in another paste exception:

PasteApplicationPublicIT.run_DirectoryNoFlag_ThrowsException:179 expected: <paste: dir: Is a directory> but was: <paste: sg.edu.nus.comp.cs4218.exception.PasteException: paste: dir: Is a directory>